DROP TABLE IF EXISTS ITEM_GROUPS;
CREATE TABLE ITEM_GROUPS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100) NULL,
    COMPLETED BIT
);

ALTER TABLE ITEMS ADD COLUMN ITEM_GROUP_ID BIGINT NULL;
ALTER TABLE ITEMS ADD FOREIGN KEY (ITEM_GROUP_ID) REFERENCES ITEM_GROUPS (ID);