DROP TABLE IF EXISTS TEMPLATES;
CREATE TABLE TEMPLATES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100) NULL,
    CREATE_TIME DATETIME NULL,
    LAST_EDIT_TIME DATETIME NULL
);

ALTER TABLE ITEM_GROUPS ADD COLUMN TEMPLATE_ID BIGINT NULL;
ALTER TABLE ITEM_GROUPS ADD FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES (ID);