DROP TABLE IF EXISTS TEMPLATE_STEPS;
CREATE TABLE TEMPLATE_STEPS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100) NULL,
    DEADLINE INT NOT NULL,
    TEMPLATE_ID BIGINT,
    CREATE_TIME DATETIME NULL,
    LAST_EDIT_TIME DATETIME NULL,
    FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES (ID)
);